query1 = ("SELECT "
"d.department"
", j.job"
", COUNT(CASE WHEN MONTH(e.datetime) BETWEEN 1 AND 3 THEN 1 ELSE NULL END) AS Q1 "
", COUNT(CASE WHEN MONTH(e.datetime) BETWEEN 4 AND 6 THEN 1 ELSE NULL END) AS Q2 "
", COUNT(CASE WHEN MONTH(e.datetime) BETWEEN 7 AND 9 THEN 1 ELSE NULL END) AS Q3 "
", COUNT(CASE WHEN MONTH(e.datetime) BETWEEN 10 AND 12 THEN 1 ELSE NULL END) AS Q4 "
"FROM dbo.employees e "
"RIGHT JOIN dbo.departments d "
"ON e.department_id = d.id "
"RIGHT JOIN dbo.jobs j "
"ON e.job_id = j.id "
"WHERE YEAR(e.datetime) = 2021 "
"GROUP BY "
"d.department "
", j.job "
"ORDER BY department, job ")


query2 = (
"SELECT		d.id "
", d.department "
", COUNT(1) AS hired "
"FROM		dbo.employees e "
"RIGHT JOIN	dbo.departments d "
"ON			e.department_id = d.id "
"WHERE		YEAR(e.datetime) = 2021 "
"GROUP BY	d.id,d.department "
"HAVING		COUNT(1) > (	SELECT AVG(NUM) "
"FROM (	SELECT		COUNT(datetime) AS NUM "
"FROM		dbo.employees e "
"RIGHT JOIN	dbo.departments d "
"ON			e.department_id = d.id "
"WHERE		YEAR(e.datetime) = 2021 "
"GROUP BY	d.department "
")	AS COUNTS "
") "
"ORDER BY	hired DESC"
)